<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPfwuejc\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPfwuejc/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerPfwuejc.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerPfwuejc\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerPfwuejc\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Pfwuejc',
    'container.build_id' => '491910d8',
    'container.build_time' => 1525037435,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerPfwuejc');
